# Loan Approval Prediction Project Configuration

# Data Configuration
data:
  raw_data_path: "data/raw/playground-series-s4e10"
  processed_data_path: "data/processed"
  train_file: "train.csv"
  test_file: "test.csv"
  target_column: "loan_status"

# Feature Engineering
features:
  categorical_columns:
    - "loan_grade"
    - "person_home_ownership"
    - "loan_intent"
    - "cb_person_default_on_file"
  
  numerical_columns:
    - "person_age"
    - "person_income"
    - "person_emp_length"
    - "loan_amnt"
    - "loan_int_rate"
    - "loan_percent_income"
    - "cb_person_cred_hist_length"
  
  one_hot_encode:
    - "loan_grade"
    - "person_home_ownership"
    - "loan_intent"
    - "cb_person_default_on_file"
  
  create_interactions: true
  add_clustering: true
  n_clusters: 4

# Model Configuration
models:
  lgbm:
    default_params:
      objective: "binary"
      metric: "binary_logloss"
      boosting_type: "gbdt"
      num_leaves: 31
      learning_rate: 0.1
      feature_fraction: 0.9
      bagging_fraction: 0.8
      bagging_freq: 5
      verbose: -1
      random_state: 42
      class_weight: "balanced"
    
    hyperopt:
      max_evals: 50
      cv_folds: 3
  
  xgb:
    default_params:
      objective: "binary:logistic"
      eval_metric: "logloss"
      max_depth: 6
      learning_rate: 0.1
      n_estimators: 100
      random_state: 42
      verbosity: 0

# Training Configuration
training:
  test_size: 0.3
  random_state: 42
  stratify: true
  
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc"

# Output Configuration
outputs:
  models_dir: "models"
  plots_dir: "outputs/plots"
  reports_dir: "outputs/reports"
  
  model_artifacts:
    save_best_model: true
    save_feature_importance: true
    save_hyperopt_results: true
  
  visualization:
    save_plots: true
    plot_format: "png"
    plot_dpi: 300

# Logging Configuration
logging:
  level: "INFO"
  log_file: "outputs/logs/loan_approval.log"

# Experiment Tracking
experiment:
  track_experiments: true
  experiment_name: "loan_approval_prediction"
  tags:
    - "classification"
    - "loan_approval"
    - "lightgbm"
